# Generated by Django 3.1.6 on 2021-02-22 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('xp_total', models.IntegerField(default=0)),
                ('xp_to_lvlup', models.IntegerField(default=1515)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('xp', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('dateCompleted', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('xp', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('dateCompleted', models.DateTimeField()),
                ('frequency', models.CharField(max_length=40)),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('xp', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('dateCompleted', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('timePeriod', models.CharField(max_length=40)),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
