# Generated by Django 3.1.6 on 2021-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
