# Generated by Django 3.1.6 on 2021-03-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='xp_total',
            new_name='xp',
        ),
    ]
