# Generated by Django 3.1.6 on 2021-04-04 04:04

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='timePeriod',
            field=models.CharField(blank=True, max_length=40, validators=[api.helpers.validate_timeperiod]),
        ),
    ]
