# Generated by Django 3.1.6 on 2021-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210404_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='xp',
            field=models.IntegerField(default=100),
        ),
    ]
